### ISSUE TITLE
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 13246)

### ISSUE THREAD

**Issue by 0-wiz-0** [trailofbits/pip-audit#116]
I just ran pip-audit-0.0.4 for the first time and got an error:
```
Traceback (most recent call last):
  File "/usr/pkg/lib/python3.9/site-packages/pip_audit/dependency_source/pip.py", line 64, in collect
    for (_, dist) in pip_api.installed_distributions(local=self._local).items():
  File "/usr/pkg/lib/python3.9/site-packages/pip_api/_installed_distributions.py", line 83, in installed_distributions
    return _new_installed_distributions(local)
  File "/usr/pkg/lib/python3.9/site-packages/pip_api/_installed_distributions.py", line 71, in _new_installed_distributions
    for raw_dist in json.loads(result):
  File "/usr/pkg/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/pkg/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 13246)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/pkg/bin/pip-audit-3.9", line 33, in <module>
    sys.exit(load_entry_point('pip-audit==0.0.4', 'console_scripts', 'pip-audit')())
  File "/usr/pkg/lib/python3.9/site-packages/pip_audit/cli.py", line 196, in audit
    for (spec, vulns) in auditor.audit(source):
  File "/usr/pkg/lib/python3.9/site-packages/pip_audit/audit.py", line 60, in audit
    yield from self._service.query_all(specs)
  File "/usr/pkg/lib/python3.9/site-packages/pip_audit/service/interface.py", line 82, in query_all
    for spec in specs:
  File "/usr/pkg/lib/python3.9/site-packages/pip_audit/dependency_source/pip.py", line 72, in collect
    raise PipSourceError("failed to list installed distributions") from e
pip_audit.dependency_source.pip.PipSourceError: failed to list installed distributions
```

**Comment by woodruffw** [comment]
Thanks for the report. That looks like an error in `pip-api`, which we're using to provide a stable wrapper for the `pip` CLI. 

In particular, it looks like `pip list --format=json` failed to produce valid JSON. Could you share the output of that command, when run in the exact same environment that you ran `pip-audit`?

**Comment by 0-wiz-0** [comment]
Sure:
```
[{"name": "astroid", "version": "2.8.4"}, {"name": "atomicwrites", "version": "1.4.0"}, {"name": "autopep8", "version": "1.6.0"}, {"name": "Babel", "version": "2.9.1"}, {"name": "blinker", "version": "1.4"}, {"name": "borgbackup", "version": "1.1.17"}, {"name": "CacheControl", "version": "0.12.10"}, {"name": "cachetools", "version": "4.2.4"}, {"name": "certifi", "version": "2021.10.8"}, {"name": "cffi", "version": "1.14.6"}, {"name": "chardet", "version": "4.0.0"}, {"name": "charset-normalizer", "version": "2.0.7"}, {"name": "click", "version": "7.1.2"}, {"name": "click-log", "version": "0.3.2"}, {"name": "click-threading", "version": "0.5.0"}, {"name": "cmake-language-server", "version": "0.1.2"}, {"name": "codespell", "version": "2.1.0"}, {"name": "colorama", "version": "0.4.4"}, {"name": "configobj", "version": "5.0.6"}, {"name": "cryptography", "version": "3.3.2"}, {"name": "Cython", "version": "0.29.24"}, {"name": "deprecation", "version": "2.1.0"}, {"name": "eyeD3", "version": "0.9.5"}, {"name": "factory-boy", "version": "3.2.0"}, {"name": "Faker", "version": "8.13.2"}, {"name": "fileobj", "version": "0.7.106"}, {"name": "filetype", "version": "1.0.8"}, {"name": "flake8", "version": "3.9.2"}, {"name": "gaupol", "version": "0.28.2"}, {"name": "Genshi", "version": "0.7.5"}, {"name": "google-api-core", "version": "1.31.1"}, {"name": "google-api-python-client", "version": "2.15.0"}, {"name": "google-auth", "version": "1.34.0"}, {"name": "google-auth-httplib2", "version": "0.1.0"}, {"name": "googleapis-common-protos", "version": "1.53.0"}, {"name": "grpcio", "version": "1.41.1"}, {"name": "html5lib", "version": "1.1"}, {"name": "httplib2", "version": "0.20.2"}, {"name": "icalendar", "version": "4.0.7"}, {"name": "idna", "version": "2.10"}, {"name": "isort", "version": "5.9.3"}, {"name": "jedi", "version": "0.18.0"}, {"name": "khal", "version": "0.10.4"}, {"name": "khard", "version": "0.17.0"}, {"name": "lazy-object-proxy", "version": "1.6.0"}, {"name": "lockfile", "version": "0.12.2"}, {"name": "lxml", "version": "4.6.4"}, {"name": "Markdown", "version": "3.1.1"}, {"name": "mccabe", "version": "0.6.1"}, {"name": "meld", "version": "3.21.0"}, {"name": "mercurial", "version": "5.9.3"}, {"name": "meson", "version": "0.60.1"}, {"name": "msgpack", "version": "1.0.2"}, {"name": "numpy", "version": "1.21.4"}, {"name": "oauth2client", "version": "4.1.3"}, {"name": "oauthlib", "version": "3.1.1"}, {"name": "olefile", "version": "0.46"}, {"name": "packaging", "version": "21.2"}, {"name": "parso", "version": "0.8.2"}, {"name": "Pillow", "version": "8.4.0"}, {"name": "pip", "version": "20.3.3"}, {"name": "pip-api", "version": "0.0.23"}, {"name": "pip-audit", "version": "0.0.4"}, {"name": "platformdirs", "version": "2.4.0"}, {"name": "playitslowly", "version": "1.5.1"}, {"name": "pluggy", "version": "0.13.1"}, {"name": "progress", "version": "1.6"}, {"name": "protobuf", "version": "3.19.0"}, {"name": "pyasn1", "version": "0.4.8"}, {"name": "pyasn1-modules", "version": "0.2.8"}, {"name": "pycairo", "version": "1.20.1"}, {"name": "pycodestyle", "version": "2.8.0"}, {"name": "pycparser", "version": "2.20"}, {"name": "pydocstyle", "version": "3.0.0"}, {"name": "pyenchant", "version": "2.0.0"}, {"name": "pyflakes", "version": "2.4.0"}, {"name": "pygls", "version": "0.9.1"}, {"name": "Pygments", "version": "2.10.0"}, {"name": "PyGObject", "version": "3.36.1"}, {"name": "PyJWT", "version": "2.1.0"}, {"name": "pylint", "version": "2.11.1"}, {"name": "pyOpenSSL", "version": "21.0.0"}, {"name": "pyparsing", "version": "3.0.4"}, {"name": "pyserial", "version": "3.5"}, {"name": "PySocks", "version": "1.7.1"}, {"name": "python-dateutil", "version": "2.8.2"}, {"name": "python-lsp-jsonrpc", "version": "1.0.0"}, {"name": "python-lsp-server", "version": "1.2.4"}, {"name": "pytz", "version": "2021.3"}, {"name": "pyxdg", "version": "0.27"}, {"name": "requests", "version": "2.26.0"}, {"name": "requests-oauthlib", "version": "1.3.0"}, {"name": "requests-toolbelt", "version": "0.9.1"}, {"name": "resolvelib", "version": "0.8.1"}, {"name": "rope", "version": "0.21.0"}, {"name": "rsa", "version": "4.7.2"}, {"name": "ruamel.yaml", "version": "0.17.17"}, {"name": "ruamel.yaml.clib", "version": "0.2.6"}, {"name": "scour", "version": "0.38.2"}, {"name": "setproctitle", "version": "1.2.2"}, {"name": "setuptools", "version": "57.5.0"}, {"name": "six", "version": "1.16.0"}, {"name": "snowballstemmer", "version": "2.1.0"}, {"name": "text-unidecode", "version": "1.3"}, {"name": "toml", "version": "0.10.2"}, {"name": "typed-ast", "version": "1.4.3"}, {"name": "typing-extensions", "version": "3.10.0.2"}, {"name": "tzlocal", "version": "2.1"}, {"name": "ujson", "version": "4.2.0"}, {"name": "Unidecode", "version": "1.2.0"}, {"name": "uritemplate", "version": "4.1.1"}, {"name": "urllib3", "version": "1.26.7"}, {"name": "urwid", "version": "2.1.2"}, {"name": "vdirsyncer", "version": "0.18.0"}, {"name": "vobject", "version": "0.9.6.1"}, {"name": "webencodings", "version": "0.5.1"}, {"name": "wrapt", "version": "1.13.3"}, {"name": "yapf", "version": "0.31.0"}]
```

**Comment by 0-wiz-0** [comment]
Hm, that file does not have 13k chars and jq is fine with it.

**Comment by woodruffw** [comment]
Yeah, that has `5105` according to `wc -c`. Interesting. Does the error reproduce reliably, with the same exception/exception state? Or does the offset in the decoding error vary?

**Comment by 0-wiz-0** [comment]
No, on this run I got:
```
pip-audit

Traceback (most recent call last):
  File "/usr/pkg/bin/pip-audit-3.9", line 33, in <module>
    sys.exit(load_entry_point('pip-audit==0.0.4', 'console_scripts', 'pip-audit')())
  File "/usr/pkg/lib/python3.9/site-packages/pip_audit/cli.py", line 196, in audit
    for (spec, vulns) in auditor.audit(source):
  File "/usr/pkg/lib/python3.9/site-packages/pip_audit/audit.py", line 60, in audit
    yield from self._service.query_all(specs)
  File "/usr/pkg/lib/python3.9/site-packages/pip_audit/service/interface.py", line 83, in query_all
    yield (spec, self.query(spec))
  File "/usr/pkg/lib/python3.9/site-packages/pip_audit/service/pypi.py", line 149, in query
    response: requests.Response = self.session.get(url=url)
  File "/usr/pkg/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/pkg/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/pkg/lib/python3.9/site-packages/requests/sessions.py", line 697, in send
    r.content
  File "/usr/pkg/lib/python3.9/site-packages/requests/models.py", line 836, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/pkg/lib/python3.9/site-packages/requests/models.py", line 758, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/pkg/lib/python3.9/site-packages/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/pkg/lib/python3.9/site-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/pkg/lib/python3.9/site-packages/cachecontrol/filewrapper.py", line 96, in read
    self._close()
  File "/usr/pkg/lib/python3.9/site-packages/cachecontrol/filewrapper.py", line 76, in _close
    self.__callback(result)
  File "/usr/pkg/lib/python3.9/site-packages/cachecontrol/controller.py", line 329, in cache_response
    self.cache.set(
TypeError: set() got an unexpected keyword argument 'expires'
```

**Comment by woodruffw** [comment]
Hmm, you shouldn't be seeing that at all on `0.0.4` -- that `expires` kwarg was added as part of a dep bump in 185c7a2 (which hasn't been released yet). Or is that a local installation from the repo? If so, you might need to re-install/upgrade the dependencies.

**Comment by 0-wiz-0** [comment]
Oh, I overrode the CacheControl dependency because pkgsrc already has 0.12.10 - thanks, I'll try that patch.

**Comment by 0-wiz-0** [comment]
With 0.0.4, that patch and CacheControl 0.12.10 I see:
```
Traceback (most recent call last):
  File "/usr/pkg/bin/pip-audit-3.9", line 33, in <module>
    sys.exit(load_entry_point('pip-audit==0.0.4', 'console_scripts', 'pip-audit')())
  File "/usr/pkg/lib/python3.9/site-packages/pip_audit/cli.py", line 198, in audit
    state.update_state(f"Auditing {spec.package} ({spec.version})")
AttributeError: 'Dependency' object has no attribute 'package'
```

**Comment by woodruffw** [comment]
Oh, that one's a genuine bug! Sorry for pushing a broken release. There's a fix on #109, but I'll create a hotfix PR and cut a new release now.

**Comment by woodruffw** [comment]
@0-wiz-0 could you try patching with the changes that were just merged on #117? I'll cut a new release with them as well, once we get the other things in #115 hammered out.

**Comment by 0-wiz-0** [comment]
Yes, with that applied it works nicely!
```
\ Auditing Faker (8.13.2)               WARNING:pip_audit.service.pypi:Warning: Dependency not found on PyPI and could not beaudited: fileobj (0.7.106)
- Auditing flake8 (3.9.2)               WARNING:pip_audit.service.pypi:Warning: Dependency not found on PyPI and could not beaudited: gaupol (0.28.2)
\ Auditing mccabe (0.6.1)                   WARNING:pip_audit.service.pypi:Warning: Dependency not found on PyPI and could not beaudited: meld (3.21.0)
- Auditing platformdirs (2.4.0)             WARNING:pip_audit.service.pypi:Warning: Dependency not found on PyPI and could not beaudited: playitslowly (1.5.1)
| Auditing yapf (0.31.0)                    
No known vulnerabilities found
```

Thanks for the great support!

**Comment by woodruffw** [comment]
Fantastic, glad to hear it! I'll close this out then.

(BTW, let us know if you're seeing bad rendering with the progress spinner. We're still working out some kinks with it.)

**Comment by 0-wiz-0** [comment]
The spinner looks fine. Just the WARNINGS break it (see above) but I see that as a minor issue.

**Comment by woodruffw** [comment]
> The spinner looks fine. Just the WARNINGS break it (see above) but I see that as a minor issue.

Good to know. The warnings should't be breaking it, but that is indeed minor. I wonder if it's related to the JSON issue we're seeing in #115, since that might be another case of stream confusion.

**Comment by 0-wiz-0** [comment]
Well, there is only one terminal where the spinner and the WARNINGS go -- the WARNING ends with a newline, so the CR to reset to the position of the spinner at the start of the line cannot work as intended.
