### ISSUE TITLE
`ResolutionImpossible` errors in requirements mode

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/pip-audit#197]
This is a follow-on from #159, which got closed because the surface-level bug was fixed.

Reproduction steps:

1. Create a `requirements.txt` that looks like this:

    ```
    pip-audit==1.1.1
    ```

1. Run `pip-audit -r requirements.txt`

1. Observe the error:

```
Traceback (most recent call last):
  File "/Users/william/devel/pip-audit/env/bin/pip-audit", line 33, in <module>
    sys.exit(load_entry_point('pip-audit', 'console_scripts', 'pip-audit')())
  File "/Users/william/devel/pip-audit/pip_audit/_cli.py", line 268, in audit
    for (spec, vulns) in auditor.audit(source):
  File "/Users/william/devel/pip-audit/pip_audit/_audit.py", line 60, in audit
    yield from self._service.query_all(specs)
  File "/Users/william/devel/pip-audit/pip_audit/_service/interface.py", line 115, in query_all
    for spec in specs:
  File "/Users/william/devel/pip-audit/pip_audit/_dependency_source/requirement.py", line 63, in collect
    for _, deps in self.resolver.resolve_all(iter(req_values)):
  File "/Users/william/devel/pip-audit/pip_audit/_dependency_source/interface.py", line 67, in resolve_all
    yield (req, self.resolve(req))
  File "/Users/william/devel/pip-audit/pip_audit/_dependency_source/resolvelib/resolvelib.py", line 53, in resolve
    result = self.resolver.resolve([req])
  File "/Users/william/devel/pip-audit/env/lib/python3.10/site-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/william/devel/pip-audit/env/lib/python3.10/site-packages/resolvelib/resolvers.py", line 385, in resolve
    raise ResolutionImpossible(self.state.backtrack_causes)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=<Requirement('setuptools==57.4.0')>, parent=<progress==1.6 wheel=False>), RequirementInformation(requirement=<Requirement('setuptools<51.0.0,>=50.3.2')>, parent=<cyclonedx-python-lib==0.11.1 wheel=True>)]
```

**Comment by woodruffw** [comment]
Just tried repro-ing this and couldn't, with either of these `requirements.txt` inputs:

```
pip-audit==1.1.1
```

or:

```
pip-audit==2.1.1
```
