### ISSUE TITLE
Bug: `IPy==1.01` transformed to 1.1, which doesn't have hashes on PyPI

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/pip-audit#261]
This was observed experimentally: the following requirements file:

```
IPy==1.01 --hash=sha256:edeca741dea2d54aca568fa23740288c3fe86c0f3ea700344571e9ef14a7cc1a
```

Produces:

```console
$ pip-audit -r requirements.txt --require-hashes

Traceback (most recent call last):
  File "/Users/william/.pyenv/versions/3.10.0/bin/pip-audit", line 8, in <module>
    sys.exit(audit())
  File "/Users/william/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pip_audit/_cli.py", line 357, in audit
    for (spec, vulns) in auditor.audit(source):
  File "/Users/william/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pip_audit/_audit.py", line 66, in audit
    for dep, vulns in self._service.query_all(specs):
  File "/Users/william/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pip_audit/_service/interface.py", line 143, in query_all
    yield self.query(spec)
  File "/Users/william/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pip_audit/_service/pypi.py", line 78, in query
    raise ServiceError(
pip_audit._service.interface.ServiceError: Could not find release to compare hashes: ipy (1.1)
```

Note that we've normalized version `1.01` to `1.1`, while PyPI keeps it as `1.01`:

<img width="1191" alt="Screen Shot 2022-05-01 at 9 35 26 PM" src="https://user-images.githubusercontent.com/3059210/166181262-59042e6b-77d6-40e4-883c-e5a68da7e76a.png">

**Comment by woodruffw** [comment]
Specifically, it looks like this happens in `Version`:

```
>>> from pip_api import Version
>>> Version("1.01")
<Version('1.1')>
```
