### ISSUE TITLE
KeyError: "releases" for click, requests, urllib3, and more

### ISSUE THREAD

**Issue by juspence** [trailofbits/pip-audit#317]
## Bug description

KeyError: "releases" and a traceback is seen when auditing certain dependencies. It looks like the PyPI data format changed for some recently-updated packages (or this is a PyPI bug).

## Reproduction steps

```
curl https://pypi.org/pypi/requests-gssapi/1.2.3/json | jq .releases
curl https://pypi.org/pypi/click/json | jq .releases
curl https://pypi.org/pypi/click/8.0.3/json | jq .releases
# First and second have releases, third does not
pip-audit -r requirements/base.txt
```
With a requirements file like:
```
click==8.0.3 \
    --hash=sha256:353f466495adaeb40b6b5f592f9f91cb22372351c84caeb068132442a4518ef3 \
    --hash=sha256:410e932b050f5eed773c4cda94de75971c89cdb3155a72a0831139a79e5ecb5b
```
Removing the hashes makes the pip-audit command succeed, so I'm leaning towards this being a pip-audit bug.

## Expected behavior

pip-tools can handle the (possibly changed?) data format returned by PyPI.

## Screenshots and logs

When only click==8.0.3 with hashes is audited:
```
DEBUG:pip_audit._cli:parsed arguments: Namespace(local=False, requirements=[<_io.TextIOWrapper name='requirements/base.txt' mode='r' encoding='UTF-8'>], project_path=None, format=<OutputFormatChoice.Columns: 'columns'>, vulnerability_service=<VulnerabilityServiceChoice.Pypi: 'pypi'>, dry_run=False, strict=False, desc=<VulnerabilityDescriptionChoice.Auto: 'auto'>, cache_dir=None, progress_spinner=<ProgressSpinnerChoice.On: 'on'>, timeout=15, paths=[], verbose=True, fix=False, require_hashes=False, index_url='https://pypi.org/simple', extra_index_urls=[], skip_editable=False, no_deps=False, output=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>, ignore_vulns=[])
DEBUG:cachecontrol.controller:Looking up "https://pypi.org/pypi/click/8.0.3/json" in the cache
DEBUG:cachecontrol.controller:Current age based on date: 504
DEBUG:cachecontrol.controller:Freshness lifetime from max-age: 900
DEBUG:cachecontrol.controller:The response is "fresh", returning cached response
DEBUG:cachecontrol.controller:900 > 504
Traceback (most recent call last):
  File "/home/user/Desktop/repos/sdengine/venv/bin/pip-audit", line 8, in <module>
    sys.exit(audit())
  File "/home/user/Desktop/repos/sdengine/venv/lib/python3.9/site-packages/pip_audit/_cli.py", line 428, in audit
    for (spec, vulns) in auditor.audit(source):
  File "/home/user/Desktop/repos/sdengine/venv/lib/python3.9/site-packages/pip_audit/_audit.py", line 66, in audit
    for dep, vulns in self._service.query_all(specs):
  File "/home/user/Desktop/repos/sdengine/venv/lib/python3.9/site-packages/pip_audit/_service/interface.py", line 149, in query_all
    yield self.query(spec)
  File "/home/user/Desktop/repos/sdengine/venv/lib/python3.9/site-packages/pip_audit/_service/pypi.py", line 94, in query
    for r, v in response_json["releases"].items():
KeyError: 'releases'
```

When only click==8.0.3 without hashes is audited:
```
DEBUG:pip_audit._cli:parsed arguments: Namespace(local=False, requirements=[<_io.TextIOWrapper name='requirements/base.txt' mode='r' encoding='UTF-8'>], project_path=None, format=<OutputFormatChoice.Columns: 'columns'>, vulnerability_service=<VulnerabilityServiceChoice.Pypi: 'pypi'>, dry_run=False, strict=False, desc=<VulnerabilityDescriptionChoice.Auto: 'auto'>, cache_dir=None, progress_spinner=<ProgressSpinnerChoice.On: 'on'>, timeout=15, paths=[], verbose=True, fix=False, require_hashes=False, index_url='https://pypi.org/simple', extra_index_urls=[], skip_editable=False, no_deps=False, output=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>, ignore_vulns=[])
DEBUG:cachecontrol.controller:Looking up "https://pypi.org/simple/click" in the cache
DEBUG:cachecontrol.controller:Returning cached permanent redirect response (ignoring date and etag information)
DEBUG:cachecontrol.controller:Looking up "https://pypi.org/simple/click/" in the cache
DEBUG:cachecontrol.controller:Current age based on date: 518
DEBUG:cachecontrol.controller:Freshness lifetime from max-age: 600
DEBUG:cachecontrol.controller:The response is "fresh", returning cached response
DEBUG:cachecontrol.controller:600 > 518
DEBUG:cachecontrol.controller:Looking up "https://files.pythonhosted.org/packages/48/58/c8aa6a8e62cc75f39fee1092c45d6b6ba684122697d7ce7d53f64f98a129/click-8.0.3-py3-none-any.whl" in the cache
DEBUG:cachecontrol.controller:Current age based on date: 517
DEBUG:cachecontrol.controller:Ignoring unknown cache-control directive: immutable
DEBUG:cachecontrol.controller:Freshness lifetime from max-age: 365000000
DEBUG:cachecontrol.controller:The response is "fresh", returning cached response
DEBUG:cachecontrol.controller:365000000 > 517
DEBUG:cachecontrol.controller:Looking up "https://pypi.org/pypi/click/8.0.3/json" in the cache
DEBUG:cachecontrol.controller:Current age based on date: 10
DEBUG:cachecontrol.controller:Freshness lifetime from max-age: 900
DEBUG:cachecontrol.controller:The response is "fresh", returning cached response
DEBUG:cachecontrol.controller:900 > 10
No known vulnerabilities found
```

## Platform information

* OS name and version: RHEL 8.6 and our CI system in Gitlab (AKA, not a local cache issue)
* `pip-audit` version (`pip-audit -V`): 2.3.0 and 2.4.0
* Python version (`python -V` or `python3 -V`): Python 3.9.7
* `pip` version (`pip -V` or `pip3 -V`): pip 22.0.4 from venv/lib/python3.9/site-packages/pip (python 3.9)

I can provide more information if needed, or please let me know if I should refile as a PyPI bug. I can't tell if this change is being rolled out gradually when packages are updated, or if it's a bug.

**Comment by di** [comment]
This is due to https://discuss.python.org/t/backwards-incompatible-change-to-pypi-json-api/. We shouldn't expect this to come back, so we should adapt to using the un-versioned URL instead.

**Comment by woodruffw** [comment]
Yeah, I can tackle this now. Thanks for the report @juspence!

**Comment by woodruffw** [comment]
> We shouldn't expect this to come back, so we should adapt to using the un-versioned URL instead.

We can actually avoid a separate request entirely, since the `urls` array is still present and contains a `digests` object within each parent object, e.g.:

```json
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "f4399393e58c56b25d9b9e8a665d2255",
        "sha256": "353f466495adaeb40b6b5f592f9f91cb22372351c84caeb068132442a4518ef3"
      },
      "downloads": -1,
      "filename": "click-8.0.3-py3-none-any.whl",
      "has_sig": true,
      "md5_digest": "f4399393e58c56b25d9b9e8a665d2255",
      "packagetype": "bdist_wheel",
      "python_version": "py3",
      "requires_python": ">=3.6",
      "size": 97516,
      "upload_time": "2021-10-10T18:07:30",
      "upload_time_iso_8601": "2021-10-10T18:07:30.752051Z",
      "url": "https://files.pythonhosted.org/packages/48/58/c8aa6a8e62cc75f39fee1092c45d6b6ba684122697d7ce7d53f64f98a129/click-8.0.3-py3-none-any.whl",
      "yanked": false,
      "yanked_reason": null
    },
    {
      "comment_text": "",
      "digests": {
        "md5": "6bcf62c52c6b58c9977c7d19b0d0cbf9",
        "sha256": "410e932b050f5eed773c4cda94de75971c89cdb3155a72a0831139a79e5ecb5b"
      },
      "downloads": -1,
      "filename": "click-8.0.3.tar.gz",
      "has_sig": true,
      "md5_digest": "6bcf62c52c6b58c9977c7d19b0d0cbf9",
      "packagetype": "sdist",
      "python_version": "source",
      "requires_python": ">=3.6",
      "size": 329034,
      "upload_time": "2021-10-10T18:07:33",
      "upload_time_iso_8601": "2021-10-10T18:07:33.001103Z",
      "url": "https://files.pythonhosted.org/packages/f4/09/ad003f1e3428017d1c3da4ccc9547591703ffea548626f47ec74509c5824/click-8.0.3.tar.gz",
      "yanked": false,
      "yanked_reason": null
    }
  ],
```

So our current approach was already suboptimal, doing this should be slightly faster anyways!

**Comment by juspence** [comment]
@woodruffw Works for me, thanks for the quick fix!

**Comment by woodruffw** [comment]
No problem! Thanks for the report and confirmation!
