### ISSUE TITLE
Random failures if requirements contain uwsgi package

### ISSUE THREAD

**Issue by heck-gd** [trailofbits/pip-audit#349]
## Bug description

We use pip-audit in our CI in order to audit requirements files of Python projects. All projects that depend on `uwsgi` have highly undeterministic auditing stage failures. Sometimes we have 3 failed runs in a row, sometimes it works 20 times in a row without issues.

Note: We've never ever had a problem with installing `uwsgi` using pip in the actual projects (which also run in Debian-based Python Docker images). It only fails in pip-audit.

## Reproduction steps

1. Build the Docker image given below.
2. Create `requirements.txt` with content `uwsgi==2.0.20`. Using `uwsgi~=2.0.20` shouldn't make a difference in terms of this bug.
3. Run `docker run --rm -v $(pwd):/work pip-audit:latest pip-audit -v -r /work/requirements.txt --progress-spinner off` repeatedly until an exception occurs. This can take quite some patience.

## Expected behavior

pip-audit behaves deterministically and doesn't randomly fail installing packages.

## Screenshots and logs

```
DEBUG:pip_audit._cli:parsed arguments: Namespace(local=False, requirements=[<_io.TextIOWrapper name='/work/requirements.txt' mode='r' encoding='UTF-8'>], project_path=None, format=<OutputFormatChoice.Columns: 'columns'>, vulnerability_service=<VulnerabilityServiceChoice.Pypi: 'pypi'>, dry_run=False, strict=False, desc=<VulnerabilityDescriptionChoice.Auto: 'auto'>, cache_dir=None, progress_spinner=<ProgressSpinnerChoice.Off: 'off'>, timeout=15, paths=[], verbose=True, fix=False, require_hashes=False, index_url='https://pypi.org/simple', extra_index_urls=[], skip_editable=False, no_deps=False, output=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>, ignore_vulns=[])
DEBUG:cachecontrol.controller:Looking up "https://pypi.org/simple/uwsgi" in the cache
DEBUG:cachecontrol.controller:No cache entry available
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): pypi.org:443
DEBUG:urllib3.connectionpool:https://pypi.org:443 "GET /simple/uwsgi HTTP/1.1" 301 111
DEBUG:cachecontrol.controller:Updating cache with response from "https://pypi.org/simple/uwsgi"
DEBUG:cachecontrol.controller:Caching permanent redirect
DEBUG:cachecontrol.controller:Looking up "https://pypi.org/simple/uwsgi/" in the cache
DEBUG:cachecontrol.controller:No cache entry available
DEBUG:urllib3.connectionpool:https://pypi.org:443 "GET /simple/uwsgi/ HTTP/1.1" 200 5130
DEBUG:cachecontrol.controller:Updating cache with response from "https://pypi.org/simple/uwsgi/"
DEBUG:cachecontrol.controller:etag object cached for 1209600 seconds
DEBUG:cachecontrol.controller:Caching due to etag
DEBUG:cachecontrol.controller:Looking up "https://files.pythonhosted.org/packages/24/fd/93851e4a076719199868d4c918cc93a52742e68370188c1c570a6e42a54f/uwsgi-2.0.20.tar.gz" in the cache
DEBUG:cachecontrol.controller:No cache entry available
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): files.pythonhosted.org:443
DEBUG:urllib3.connectionpool:https://files.pythonhosted.org:443 "GET /packages/24/fd/93851e4a076719199868d4c918cc93a52742e68370188c1c570a6e42a54f/uwsgi-2.0.20.tar.gz HTTP/1.1" 200 804906
DEBUG:cachecontrol.controller:Ignoring unknown cache-control directive: immutable
DEBUG:cachecontrol.controller:Updating cache with response from "https://files.pythonhosted.org/packages/24/fd/93851e4a076719199868d4c918cc93a52742e68370188c1c570a6e42a54f/uwsgi-2.0.20.tar.gz"
DEBUG:cachecontrol.controller:etag object cached for 1209600 seconds
DEBUG:cachecontrol.controller:Caching due to etag
Traceback (most recent call last):
  File "/app/.local/lib/python3.10/site-packages/pip_audit/_virtual_env.py", line 104, in post_setup
    run(package_install_cmd, state=self._state)
  File "/app/.local/lib/python3.10/site-packages/pip_audit/_subprocess.py", line 51, in run
    raise CalledProcessError(f"{pretty_args} exited with {process.returncode}")
pip_audit._subprocess.CalledProcessError: python -m pip install /tmp/tmpoec42g0s/uwsgi-2.0.20.tar.gz exited with 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.local/bin/pip-audit", line 8, in <module>
    sys.exit(audit())
  File "/app/.local/lib/python3.10/site-packages/pip_audit/_cli.py", line 428, in audit
    for (spec, vulns) in auditor.audit(source):
  File "/app/.local/lib/python3.10/site-packages/pip_audit/_audit.py", line 66, in audit
    for dep, vulns in self._service.query_all(specs):
  File "/app/.local/lib/python3.10/site-packages/pip_audit/_service/interface.py", line 148, in query_all
    for spec in specs:
  File "/app/.local/lib/python3.10/site-packages/pip_audit/_dependency_source/requirement.py", line 120, in collect
    for _, dep in self._collect_cached_deps(filename, reqs):
  File "/app/.local/lib/python3.10/site-packages/pip_audit/_dependency_source/requirement.py", line 320, in _collect_cached_deps
    for req, resolved_deps in self._resolver.resolve_all(iter(req_values)):
  File "/app/.local/lib/python3.10/site-packages/pip_audit/_dependency_source/interface.py", line 87, in resolve_all
    yield (req, self.resolve(req))
  File "/app/.local/lib/python3.10/site-packages/pip_audit/_dependency_source/resolvelib/resolvelib.py", line 75, in resolve
    result = self.resolver.resolve([req])
  File "/app/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/app/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/app/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/app/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 203, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "/app/.local/lib/python3.10/site-packages/pip_audit/_dependency_source/resolvelib/pypi_provider.py", line 370, in get_dependencies
    return candidate.dependencies
  File "/app/.local/lib/python3.10/site-packages/pip_audit/_dependency_source/resolvelib/pypi_provider.py", line 120, in dependencies
    self._dependencies = list(self._get_dependencies())
  File "/app/.local/lib/python3.10/site-packages/pip_audit/_dependency_source/resolvelib/pypi_provider.py", line 102, in _get_dependencies
    deps: List[str] = self.metadata.get_all("Requires-Dist", [])
  File "/app/.local/lib/python3.10/site-packages/pip_audit/_dependency_source/resolvelib/pypi_provider.py", line 95, in metadata
    self._metadata = self._get_metadata_for_sdist()
  File "/app/.local/lib/python3.10/site-packages/pip_audit/_dependency_source/resolvelib/pypi_provider.py", line 163, in _get_metadata_for_sdist
    ve.create(ve_dir)
  File "/usr/local/lib/python3.10/venv/__init__.py", line 78, in create
    self.post_setup(context)
  File "/app/.local/lib/python3.10/site-packages/pip_audit/_virtual_env.py", line 106, in post_setup
    raise VirtualEnvError(f"Failed to install packages: {package_install_cmd}") from cpe
pip_audit._virtual_env.VirtualEnvError: Failed to install packages: ['/tmp/tmp3dhmfebg/bin/python', '-m', 'pip', 'install', '/tmp/tmpoec42g0s/uwsgi-2.0.20.tar.gz']
```

## Platform information

* OS name and version: python:3.10.6-slim-bullseye Docker image (see below)
* `pip-audit` version (`pip-audit -V`): 2.4.3
* Python version (`python -V` or `python3 -V`): 3.10.6
* `pip` version (`pip -V` or `pip3 -V`): 22.2.1

## Additional context

The Dockerfile that builds our pip-audit image:
```dockerfile
FROM python:3.10.6-slim-bullseye@sha256:2124d4f8ccbd537500de16660a876263949ed9a9627cfb6141f418d36f008e9e

RUN apt-get update && apt-get full-upgrade -y \
    && apt-get autoremove && apt-get clean \
    && apt-get install --no-install-recommends --no-install-suggests -y build-essential \
    && rm -rf /var/lib/apt/lists/* \
    && useradd -m -d /app pip-audit
WORKDIR /app
COPY requirements.txt .

# We install pip-audit into the user's $HOME in order to prevent polluting /
USER pip-audit
RUN pip3 install --no-cache-dir -r requirements.txt
ENV PATH="${PATH}:/app/.local/bin"

USER root
RUN rm /usr/local/bin/pip* && dpkg --purge --force-remove-essential,depends dpkg apt
USER pip-audit
```

requirements.txt referenced therein:
```
pip-audit==2.4.3
```

**Comment by woodruffw** [comment]
Just some notes for myself: `uwsgi` is sdist-only, which is too bad. That means that `pip-audit` is taking the sdist metadata path, and the failure clearly happens intermittently during installation so that we can extract that metadata.

**Comment by woodruffw** [comment]
Possibly related: https://github.com/unbit/uwsgi/issues/2471

**Comment by woodruffw** [comment]
Yeah, this appears to be a known issue: https://github.com/unbit/uwsgi/commit/1bb9ad77c6d2d310c2d6d1d9ad62de61f725b824

**Comment by heck-gd** [comment]
I see, thanks for pointing that out. That actually explains why we haven't seen this failure elsewhere, because our project images are still based on Debian Buster.

I'm closing this since it's not an issue with pip-audit after all. We're going to wait for a newer uwsgi release or downgrade our pip-audit image to Buster.

Thanks for your quick response!

**Comment by woodruffw** [comment]
No problem, thanks for the report! This demonstrates that we probably need some better error handling and messaging here, so thanks!
