### ISSUE TITLE
Cannot audit requirements.txt containing URL dependencies

### ISSUE THREAD

**Issue by rooterkyberian** [trailofbits/pip-audit#354]
## Bug description

Cannot produce an audit for a file containing URL dependencies.

## Reproduction steps

requirements-lock.txt
```
de-core-news-sm @ https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.2.0/de_core_news_sm-3.2.0.tar.gz
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.2.0/en_core_web_sm-3.2.0.tar.gz
httplib2==0.9.1
```

```
$ pip-audit -r requirements-lock.txt --no-deps --skip-editable
WARNING:pip_audit._cli:--no-deps is supported, but users are encouraged to fully hash their pinned dependencies
WARNING:pip_audit._cli:Consider using a tool like `pip-compile`: https://pip-tools.readthedocs.io/en/latest/#using-hashes
WARNING:pip_audit._cache:Warning: pip 20.0.2 doesn't support the `cache dir` subcommand, using /home/rooter/.pip-audit-cache instead
Traceback (most recent call last):
  File "/projects/dummy/.venv/bin/pip-audit", line 8, in <module>
    sys.exit(audit())
  File "/projects/dummy/.venv/lib/python3.8/site-packages/pip_audit/_cli.py", line 428, in audit
    for (spec, vulns) in auditor.audit(source):
  File "/projects/dummy/.venv/lib/python3.8/site-packages/pip_audit/_audit.py", line 66, in audit
    for dep, vulns in self._service.query_all(specs):
  File "/projects/dummy/.venv/lib/python3.8/site-packages/pip_audit/_service/interface.py", line 148, in query_all
    for spec in specs:
  File "/projects/dummy/.venv/lib/python3.8/site-packages/pip_audit/_dependency_source/requirement.py", line 120, in collect
    for _, dep in self._collect_cached_deps(filename, reqs):
  File "/projects/dummy/.venv/lib/python3.8/site-packages/pip_audit/_dependency_source/requirement.py", line 310, in _collect_cached_deps
    for req, dep in self._collect_preresolved_deps(
  File "/projects/dummy/.venv/lib/python3.8/site-packages/pip_audit/_dependency_source/requirement.py", line 260, in _collect_preresolved_deps
    raise RequirementSourceError(f"requirement {req.name} is not pinned: {str(req)}")
pip_audit._dependency_source.requirement.RequirementSourceError: requirement de-core-news-sm is not pinned: de-core-news-sm@ https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.2.0/de_core_news_sm-3.2.0.tar.gz from https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.2.0/de_core_news_sm-3.2.0.tar.gz (from RequirementLine(line_number=149, line='de-core-news-sm @ https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.2.0/de_core_news_sm-3.2.0.tar.gz', filename=PosixPath('requirements-lock.txt')))
```

## Expected behavior

I would like it either be automatically skipped (maybe with an error code thrown), and/or have a CLI flag that allows ignoring them completely (without error code thrown at the end).

## Screenshots and logs

```
pip-audit -r requirements.txt --no-deps --skip-editable -v
DEBUG:pip_audit._cli:parsed arguments: Namespace(cache_dir=None, desc=<VulnerabilityDescriptionChoice.Auto: 'auto'>, dry_run=False, extra_index_urls=[], fix=False, format=<OutputFormatChoice.Columns: 'columns'>, ignore_vulns=[], index_url='https://pypi.org/simple', local=False, no_deps=True, output=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>, paths=[], progress_spinner=<ProgressSpinnerChoice.On: 'on'>, project_path=None, require_hashes=False, requirements=[<_io.TextIOWrapper name='requirements.txt' mode='r' encoding='UTF-8'>], skip_editable=True, strict=False, timeout=15, verbose=True, vulnerability_service=<VulnerabilityServiceChoice.Pypi: 'pypi'>)
WARNING:pip_audit._cli:--no-deps is supported, but users are encouraged to fully hash their pinned dependencies
WARNING:pip_audit._cli:Consider using a tool like `pip-compile`: https://pip-tools.readthedocs.io/en/latest/#using-hashes
WARNING:pip_audit._cache:Warning: pip 20.0.2 doesn't support the `cache dir` subcommand, using /home/rooter/.pip-audit-cache instead
Traceback (most recent call last):
  File "/projects/dummy/.venv/bin/pip-audit", line 8, in <module>
    sys.exit(audit())
  File "/projects/dummy/.venv/lib/python3.8/site-packages/pip_audit/_cli.py", line 428, in audit
    for (spec, vulns) in auditor.audit(source):
  File "/projects/dummy/.venv/lib/python3.8/site-packages/pip_audit/_audit.py", line 66, in audit
    for dep, vulns in self._service.query_all(specs):
  File "/projects/dummy/.venv/lib/python3.8/site-packages/pip_audit/_service/interface.py", line 148, in query_all
    for spec in specs:
  File "/projects/dummy/.venv/lib/python3.8/site-packages/pip_audit/_dependency_source/requirement.py", line 120, in collect
    for _, dep in self._collect_cached_deps(filename, reqs):
  File "/projects/dummy/.venv/lib/python3.8/site-packages/pip_audit/_dependency_source/requirement.py", line 310, in _collect_cached_deps
    for req, dep in self._collect_preresolved_deps(
  File "/projects/dummy/.venv/lib/python3.8/site-packages/pip_audit/_dependency_source/requirement.py", line 260, in _collect_preresolved_deps
    raise RequirementSourceError(f"requirement {req.name} is not pinned: {str(req)}")
pip_audit._dependency_source.requirement.RequirementSourceError: requirement de-core-news-sm is not pinned: de-core-news-sm@ https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.2.0/de_core_news_sm-3.2.0.tar.gz from https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.2.0/de_core_news_sm-3.2.0.tar.gz (from RequirementLine(line_number=1, line='de-core-news-sm @ https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.2.0/de_core_news_sm-3.2.0.tar.gz', filename=PosixPath('requirements.txt')))
```

## Platform information

* OS name and version: Ubuntu 20.04.4 LTS
* `pip-audit` version (`pip-audit -V`): pip-audit 2.4.3
* Python version (`python -V` or `python3 -V`): Python 3.8.10
* `pip` version (`pip -V` or `pip3 -V`): pip 20.0.2

**Comment by tetsuo-cpp** [comment]
Thanks for reporting this @rooterkyberian. I'll take a look at this shortly.

**Comment by woodruffw** [comment]
Hmm, we should figure out the right behavior here -- `pip-audit` ultimately uses PyPI (and OSV) as a dependency source, which means that arbitrary URL-style requirements may not have corresponding packages on PyPI.

But that doesn't mean we should skip *all* URL-style requirements -- there might be cases where a user chooses to use URLs for whatever reason that *do* correspond to packages on PyPI, and we should probably audit those by default.

IMO, the right behavior here is probably to try and mirror `pip` as closely as possible -- we should support URL-style requirements and collect their transitive dependencies, but mark them as "skipped" if they don't correspond to a package on PyPI. Our pre-existing "strict" mode can then turn those skips into hard errors, as necessary.

How does that sound @tetsuo-cpp @di?

**Comment by woodruffw** [comment]
(There's a possible failure mode there where a user specifies package `foo` via a URL, but `foo` on PyPI is a completely different package that just happens to have the same name. If that happens, we may end up reporting incorrect vulnerabilities. But maybe that's an acceptable tradeoff?)

**Comment by tetsuo-cpp** [comment]
> (There's a possible failure mode there where a user specifies package `foo` via a URL, but `foo` on PyPI is a completely different package that just happens to have the same name. If that happens, we may end up reporting incorrect vulnerabilities. But maybe that's an acceptable tradeoff?)

I think that's fine. We've already accepted that trade-off in other places.

For example, for VCS requirements or those on the actual filesystem, we just get the package name and version and check it against PyPI.

`pip` itself also has the same flavour of problem where packages with the same name on different indexes are assumed to be identical.

**Comment by tetsuo-cpp** [comment]
@rooterkyberian 

The error message from `pip-audit` isn't clear, but the issue is we're supplying the `--no-deps` flag and the URL dependencies don't have a pinned version specifier. Basically, `pip-audit` doesn't download the archive and try to figure out what the package name and version is, it needs to have this information fed to it. For VCS and URL dependencies, we do this via egg fragments. So if I change the requirements file to look like this, it works fine:
```
(env) tetsuo@Alexs-MacBook-Pro pip-audit % cat requirements.txt
https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.2.0/de_core_news_sm-3.2.0.tar.gz#egg=de-core-news-sm==3.2.0
https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.2.0/en_core_web_sm-3.2.0.tar.gz#egg=en-core-web-sm==3.2.0
httplib2==0.9.1
(env) tetsuo@Alexs-MacBook-Pro pip-audit % pip-audit -r requirements.txt --no-deps
WARNING:pip_audit._cli:--no-deps is supported, but users are encouraged to fully hash their pinned dependencies
WARNING:pip_audit._cli:Consider using a tool like `pip-compile`: https://pip-tools.readthedocs.io/en/latest/#using-hashes
Found 2 known vulnerabilities in 1 package
Name     Version ID            Fix Versions
-------- ------- ------------- ------------
httplib2 0.9.1   PYSEC-2020-46 0.18.0
httplib2 0.9.1   PYSEC-2021-16 0.19.0
Name            Skip Reason
--------------- ------------------------------------------------------------------------------
de-core-news-sm Dependency not found on PyPI and could not be audited: de-core-news-sm (3.2.0)
en-core-web-sm  Dependency not found on PyPI and could not be audited: en-core-web-sm (3.2.0)
```

The first thing I want to do is modify the error message to look more like this: https://github.com/trailofbits/pip-audit/blob/main/pip_audit/_dependency_source/requirement.py#L98-L109

**Comment by tetsuo-cpp** [comment]
I also noticed a few related problems which I'll file an issue for. If I try to run an audit without pinning the version in the egg fragment and without the `--no-deps` flag, I'm seeing some weird behaviour.

Instead of adding the URL requirements to the skipped dependencies list like it does in the above example, we get a dependency resolution failure:

```
(env) tetsuo@Alexs-MacBook-Pro pip-audit % cat requirements.txt
https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.2.0/de_core_news_sm-3.2.0.tar.gz#egg=de-core-news-sm
https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.2.0/en_core_web_sm-3.2.0.tar.gz#egg=en-core-web-sm
httplib2==0.9.1
(env) tetsuo@Alexs-MacBook-Pro pip-audit % pip-audit -r requirements.txt
Traceback (most recent call last):
  File "/Users/tetsuo/Code/pip-audit/env/lib/python3.9/site-packages/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/tetsuo/Code/pip-audit/env/lib/python3.9/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    raise RequirementsConflicted(criterion)
resolvelib.resolvers.RequirementsConflicted: Requirements conflict: <Requirement('en-core-web-sm')>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tetsuo/Code/pip-audit/env/bin/pip-audit", line 8, in <module>
    sys.exit(audit())
  File "/Users/tetsuo/Code/pip-audit/pip_audit/_cli.py", line 432, in audit
    for (spec, vulns) in auditor.audit(source):
  File "/Users/tetsuo/Code/pip-audit/pip_audit/_audit.py", line 66, in audit
    for dep, vulns in self._service.query_all(specs):
  File "/Users/tetsuo/Code/pip-audit/pip_audit/_service/interface.py", line 150, in query_all
    for spec in specs:
  File "/Users/tetsuo/Code/pip-audit/pip_audit/_dependency_source/requirement.py", line 120, in collect
    for _, dep in self._collect_cached_deps(filename, reqs):
  File "/Users/tetsuo/Code/pip-audit/pip_audit/_dependency_source/requirement.py", line 320, in _collect_cached_deps
    for req, resolved_deps in self._resolver.resolve_all(iter(req_values)):
  File "/Users/tetsuo/Code/pip-audit/pip_audit/_dependency_source/interface.py", line 87, in resolve_all
    yield (req, self.resolve(req))
  File "/Users/tetsuo/Code/pip-audit/pip_audit/_dependency_source/resolvelib/resolvelib.py", line 75, in resolve
    result = self.resolver.resolve([req])
  File "/Users/tetsuo/Code/pip-audit/env/lib/python3.9/site-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/tetsuo/Code/pip-audit/env/lib/python3.9/site-packages/resolvelib/resolvers.py", line 350, in resolve
    raise ResolutionImpossible(e.criterion.information)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=<Requirement('en-core-web-sm')>, parent=None)]
```

If I use the `<name> @ <url>` syntax instead of the egg fragment, it doesn't seem to parse the package name correctly either. It still hits a requirement conflict, but there's also a parsing issue thrown in the mix.

```
(env) tetsuo@Alexs-MacBook-Pro pip-audit % cat requirements.txt
de-core-news-sm @ https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.2.0/de_core_news_sm-3.2.0.tar.gz
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.2.0/en_core_web_sm-3.2.0.tar.gz
httplib2==0.9.1
(env) tetsuo@Alexs-MacBook-Pro pip-audit % pip-audit -r requirements.txt
Traceback (most recent call last):
  File "/Users/tetsuo/Code/pip-audit/env/lib/python3.9/site-packages/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/tetsuo/Code/pip-audit/env/lib/python3.9/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    raise RequirementsConflicted(criterion)
resolvelib.resolvers.RequirementsConflicted: Requirements conflict: <Requirement('en-core-web-sm@ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.2.0/en_core_web_sm-3.2.0.tar.gz')>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tetsuo/Code/pip-audit/env/bin/pip-audit", line 8, in <module>
    sys.exit(audit())
  File "/Users/tetsuo/Code/pip-audit/pip_audit/_cli.py", line 432, in audit
    for (spec, vulns) in auditor.audit(source):
  File "/Users/tetsuo/Code/pip-audit/pip_audit/_audit.py", line 66, in audit
    for dep, vulns in self._service.query_all(specs):
  File "/Users/tetsuo/Code/pip-audit/pip_audit/_service/interface.py", line 150, in query_all
    for spec in specs:
  File "/Users/tetsuo/Code/pip-audit/pip_audit/_dependency_source/requirement.py", line 120, in collect
    for _, dep in self._collect_cached_deps(filename, reqs):
  File "/Users/tetsuo/Code/pip-audit/pip_audit/_dependency_source/requirement.py", line 320, in _collect_cached_deps
    for req, resolved_deps in self._resolver.resolve_all(iter(req_values)):
  File "/Users/tetsuo/Code/pip-audit/pip_audit/_dependency_source/interface.py", line 87, in resolve_all
    yield (req, self.resolve(req))
  File "/Users/tetsuo/Code/pip-audit/pip_audit/_dependency_source/resolvelib/resolvelib.py", line 75, in resolve
    result = self.resolver.resolve([req])
  File "/Users/tetsuo/Code/pip-audit/env/lib/python3.9/site-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/tetsuo/Code/pip-audit/env/lib/python3.9/site-packages/resolvelib/resolvers.py", line 350, in resolve
    raise ResolutionImpossible(e.criterion.information)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=<Requirement('en-core-web-sm@ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.2.0/en_core_web_sm-3.2.0.tar.gz')>, parent=None)]
```
