### ISSUE TITLE
From version 2.5.0+ there looks to be an change in behavior that breaks github actions for pip-audit

### ISSUE THREAD

**Issue by mmaeng** [trailofbits/pip-audit#569]
## Bug description
After upgrading pip-audit to >=2.5.0 there looks to be an inconsistent error when using github actions with pip-audit.  There looks like there may be a output timing change that occurred after pip-audit v2.4.13.  GHA run of pip-audit will refer to missing output.  Related issue here https://github.com/pypa/gh-action-pip-audit/issues/35

## Reproduction steps
use GHA for pip-audit https://github.com/pypa/gh-action-pip-audit
upgrade pip-audit to >=2.5.0 
random runs of pip-audit will cause this error, re-runs will randomly succeed/fail with no other changes
https://github.com/aws-cloudformation/community-registry-extensions/actions/runs/4479640468
https://github.com/aws-cloudformation/community-registry-extensions/actions/runs/4479732181
https://github.com/aws-cloudformation/community-registry-extensions/actions/runs/4479546362

downgrade to 2.4.13 resolved issue
https://github.com/aws-cloudformation/community-registry-extensions/actions/runs/4479912777

## Expected behavior
Runs succeed if no issues found

## Screenshots and logs
```
⚠️ pip-audit did not return any output
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/runpy.py", line 1[93](https://github.com/aws-cloudformation/community-registry-extensions/actions/runs/4479875961/jobs/7874420433#step:6:96), in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pip_audit/__main__.py", line 8, in <module>
    audit()
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pip_audit/_cli.py", line 449, in audit
    for spec, vulns in auditor.audit(source):
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pip_audit/_audit.py", line 67, in audit
    for dep, vulns in self._service.query_all(specs):
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pip_audit/_service/interface.py", line 154, in query_all
    for spec in specs:
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pip_audit/_dependency_source/requirement.py", line 113, in collect
    yield from self._collect_from_files([Path(f.name) for f in tmp_files])
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pip_audit/_dependency_source/requirement.py", line 147, in _collect_from_files
    ve.create(ve_dir)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/venv/__init__.py", line 71, in create
    self.post_setup(context)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pip_audit/_virtual_env.py", line 124, in post_setup
    run(package_install_cmd, log_stdout=True, state=self._state)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pip_audit/_subprocess.py", line 68, in run
    return stdout.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 4140: unexpected end of data
```
random runs of pip-audit will cause this error, re-runs will randomly succeed/fail with no other changes
https://github.com/aws-cloudformation/community-registry-extensions/actions/runs/4479640468
https://github.com/aws-cloudformation/community-registry-extensions/actions/runs/4479732181
https://github.com/aws-cloudformation/community-registry-extensions/actions/runs/4479546362

downgrade to 2.4.13 resolved issue
https://github.com/aws-cloudformation/community-registry-extensions/actions/runs/4479912777

## Platform information

* OS name and version: Ubuntu 22.04.2 LTS
* `pip-audit` version (`pip-audit -V`): 2.5.0, 2.5.1, 2.5.2
* Python version (`python -V` or `python3 -V`): 3.7, 3.8, 3.9, 3.10
* `pip` version (`pip -V` or `pip3 -V`): all recent versions from the github runner images

## Additional context

**Comment by tweirtx** [comment]
I would like to add that the same behavior is occurring in Gitlab CI on Windows (Linux appears unaffected).

**Comment by woodruffw** [comment]
Thanks for the report @mmaeng, and for confirming @tweirtx!

@mmaeng: can you share the `requirements.txt` input (or other dependency source) that you're seeing this instability with?

**Comment by woodruffw** [comment]
I believe #572 should resolve this. Could you give the changes on that branch a try and let me know if they eliminate the instability for you?

**Comment by woodruffw** [comment]
Dupe: #573.

**Comment by mmaeng** [comment]
> I believe #572 should resolve this. Could you give the changes on that branch a try and let me know if they eliminate the instability for you?

Worked in my testing!  Will upgrade again once released :)

Thanks!

**Comment by woodruffw** [comment]
Glad to hear it! We'll prep a patch release now.
