### ISSUE TITLE
ServiceError when project is not found

### ISSUE THREAD

**Issue by di** [trailofbits/pip-audit#98]
In the latest released version of `pip-audit`, when a project is installed that cannot be found on PyPI, a `ServiceError` exception is raised:

```
$ pip-audit
| Auditing future (0.18.2)
Traceback (most recent call last):
  File "/Users/dustiningram/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip_audit/service/pypi.py", line 122, in query
    response.raise_for_status()
  File "/Users/dustiningram/.pyenv/versions/3.8.2/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/pypi/gcloud/0.0.0/json/

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dustiningram/.pyenv/versions/3.8.2/bin/pip-audit", line 8, in <module>
    sys.exit(audit())
  File "/Users/dustiningram/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip_audit/cli.py", line 167, in audit
    for (spec, vulns) in auditor.audit(source):
  File "/Users/dustiningram/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip_audit/audit.py", line 53, in audit
    yield from self._service.query_all(specs)
  File "/Users/dustiningram/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip_audit/service/interface.py", line 31, in query_all
    yield (spec, self.query(spec))
  File "/Users/dustiningram/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip_audit/service/pypi.py", line 124, in query
    raise ServiceError from http_error
pip_audit.service.interface.ServiceError
```

Instead of erroring, `pip-audit` should complete the audit, and disclose that it could not audit some subset of dependencies that are present.

**Comment by di** [comment]
This also happens when a project exists, but the installed version is not found:

```
$ pip-audit
/ Auditing pexpect (4.8.0)
Traceback (most recent call last):
  File "/Users/dustiningram/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip_audit/service/pypi.py", line 122, in query
    response.raise_for_status()
  File "/Users/dustiningram/.pyenv/versions/3.8.2/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/pypi/pip/22.0.dev0/json/

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dustiningram/.pyenv/versions/3.8.2/bin/pip-audit", line 8, in <module>
    sys.exit(audit())
  File "/Users/dustiningram/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip_audit/cli.py", line 167, in audit
    for (spec, vulns) in auditor.audit(source):
  File "/Users/dustiningram/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip_audit/audit.py", line 53, in audit
    yield from self._service.query_all(specs)
  File "/Users/dustiningram/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip_audit/service/interface.py", line 31, in query_all
    yield (spec, self.query(spec))
  File "/Users/dustiningram/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip_audit/service/pypi.py", line 124, in query
    raise ServiceError from http_error
pip_audit.service.interface.ServiceError
```
